import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/app/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy", description: "How MishBaby handles account and website information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <LegalPage eyebrow="Your information" title="Privacy Policy" intro="This policy explains the current MishBaby account foundation and how information is handled when you use the website." lastUpdated="September 4, 2026">
    <section><h2>Who operates MishBaby</h2><p>MishBaby operates this website. Questions or privacy requests can be sent to <a href="mailto:mishbabyshop@gmail.com">mishbabyshop@gmail.com</a>.</p></section>
    <section><h2>Information we handle</h2><p>When you create an account, we handle your email address, authentication identifiers, login provider, and security/session information. We do not currently ask for a display name, address, payment information, or information about children. Our hosting and service providers may also process technical logs such as IP address, device information, timestamps, and error data needed to operate and secure the service.</p></section>
    <section><h2>How we use it</h2><p>Account information is used to register you, confirm your email, sign you in, recover your password, protect the service, respond to requests, and delete your account when requested. Account and security emails are transactional. Optional marketing emails require a separate, explicit opt-in and can be withdrawn anytime from the Account page. MishBaby does not automatically enroll account holders or sell personal information.</p></section>
    <section><h2>Providers and international processing</h2><p>Supabase provides authentication and account storage. Google processes information if you choose Google sign-in. Resend delivers transactional authentication emails and, when you opt in to updates, stores a synchronized email contact and subscription status for future MishBaby marketing messages. Vercel hosts the website, and Sanity supplies public catalog and editorial content. These providers may process information in countries outside Israel under their own safeguards and terms.</p></section>
    <section><h2>Amazon Creator API protection</h2><p>When you use Amazon Finds, MishBaby sends your search phrase to Amazon through the Creator API to return product results. Product pages with API-backed Amazon offers send the product&apos;s ASIN to retrieve a current attributed link. MishBaby does not store raw search phrases. To prevent abuse, the server combines your IP address with a private secret and stores only the resulting one-way hash for a fixed hourly window; the raw IP address is not stored in this feature. Hashed visitor windows are retained for no more than 48 hours and aggregate daily request totals for seven days. Amazon prices and availability are cached for no more than one hour; other Amazon API response data used here is cached for no more than 24 hours. Amazon receives information under its own privacy practices when it processes a request or when you open a result.</p></section>
    <section><h2>AliExpress API protection</h2><p>When you use AliExpress Finds, MishBaby sends your search phrase to AliExpress&apos;s affiliate product API to return English-language results. MishBaby does not request or display country-specific prices, and AliExpress confirms local currency, shipping, and availability after you open a result. MishBaby does not store raw search phrases. Search phrases are represented only by one-way cache keys, and returned product data is cached for no more than one hour. To prevent abuse, the server combines your IP address with a separate private secret and stores only the resulting one-way hash for a fixed hourly window; the raw IP address is not stored in this feature. Hashed visitor windows are retained for no more than 48 hours and aggregate daily request totals for seven days. AliExpress receives information under its own privacy practices when it processes a request or when you open a result.</p></section>
    <section><h2>Merchant click insights</h2><p>When you open a merchant offer from a curated MishBaby product page, MishBaby records an anonymous daily count containing the product, merchant, whether the link is an affiliate link, and the button location used. These counts help us understand which product offers are useful. We do not store the destination URL, your account, your email address, or a visitor-level browsing history with the click. To limit automated abuse, the server temporarily processes your IP address with a private secret and stores only the resulting one-way hash for a fixed hourly window. The raw IP address is not stored by this feature, hashed hourly records are removed within 48 hours, and anonymous daily totals are retained for no more than 24 months. A recorded click shows that a merchant link was opened; it does not establish that a purchase occurred.</p></section>
    <section><h2>Cookies, browser storage, and external merchants</h2><p>Supabase session cookies keep you securely signed in and are necessary for account functionality. MishBaby uses local browser storage to remember recent product searches, recently viewed products, and recently viewed guides on that device. This browsing history is not sent to MishBaby or synchronized with your account. You can clear recent searches and viewing history using the controls shown on the website or by clearing your browser data. MishBaby also links to affiliate merchants such as Amazon and AliExpress. Those merchants independently control their sites, checkout, cookies, and privacy practices; review their policies before purchasing.</p></section>
    <section><h2>Retention and deletion</h2><p>We retain the account while it remains active and as reasonably needed for security, legal obligations, dispute handling, and provider backup or log cycles. If you use optional email preferences, we record consent and withdrawal events with their time, source, and policy version. You can withdraw consent or permanently delete your account from the Account page. Account deletion removes MishBaby’s linked consent history from Supabase and its synchronized Resend marketing contact, subject to limited provider backup or legally required retention. You may contact us for access, correction, or deletion questions.</p></section>
    <section><h2>Adults only</h2><p>MishBaby accounts are for adults aged 18 or older. The service is parent-focused but is not intended to collect personal information directly from children. Contact us if you believe a child created an account.</p></section>
    <section><h2>Security and changes</h2><p>We use reasonable technical and organizational safeguards, but no online system is completely secure. We may update this policy as MishBaby changes and will update the date above. See our <Link href="/terms">Terms</Link> for the website rules.</p></section>
    <aside className="rounded-2xl bg-[#fff7df] p-5 text-sm text-[#735a16]"><strong>Owner review:</strong> This is a practical policy foundation, not legal advice. MishBaby’s owner should have it reviewed for the laws and markets that apply before treating it as final.</aside>
  </LegalPage>;
}
