import Link from "next/link";
import { Footer } from "./components/footer";
import { Navbar } from "./components/navbar";

const values = [
  ["✦", "Thoughtfully chosen", "A gentler place to start when everything feels like a decision."],
  ["♡", "Parent-first guidance", "Practical, honest help for the days that don't come with a manual."],
  ["↗", "More ways to shop", "We’re building a clearer way to compare the best places to buy."],
];

export default function Home() {
  return <div className="flex min-h-screen flex-col overflow-hidden"><Navbar /><main className="flex-1">
    <section className="relative isolate overflow-hidden bg-[#fff7f2]"><div className="absolute -right-28 top-8 -z-10 size-96 rounded-full bg-[#f6c9c0]/55 blur-3xl" /><div className="absolute -bottom-20 -left-20 -z-10 size-72 rounded-full bg-[#cae0d1]/75 blur-2xl" /><div className="mx-auto grid max-w-6xl gap-12 px-5 py-18 sm:px-8 md:grid-cols-[1.08fr_.92fr] md:items-center md:py-28"><div><p className="inline-flex rounded-full bg-white px-4 py-2 text-xs font-extrabold uppercase tracking-[0.14em] text-[#d9776a] shadow-sm">A softer start for parents</p><h1 className="mt-6 max-w-2xl font-display text-5xl font-semibold leading-[1.04] tracking-[-0.055em] text-[#25433a] sm:text-6xl">Good things for your <span className="text-[#d9776a]">little love.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-[#25433a]/70">MishBaby is a thoughtful place to discover baby essentials, helpful advice, and parent-approved finds—without the overwhelm.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#" className="rounded-full bg-[#25433a] px-6 py-3.5 text-sm font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-[#365c50]">Start discovering</Link><Link href="#" className="rounded-full border border-[#25433a]/15 bg-white/70 px-6 py-3.5 text-sm font-extrabold text-[#25433a] transition hover:border-[#d9776a]">How MishBaby helps</Link></div></div><div className="relative mx-auto w-full max-w-md"><div className="rounded-[2.5rem] bg-[#cae0d1] p-5 shadow-[0_24px_60px_-28px_rgba(37,67,58,.45)]"><div className="flex aspect-[4/4.6] items-center justify-center rounded-[2rem] border border-white/65 bg-[#f8ede4] p-8 text-center"><div><div className="mx-auto grid size-28 place-items-center rounded-full bg-[#f6c9c0] text-5xl shadow-sm">♡</div><p className="mt-6 font-display text-3xl font-semibold leading-tight text-[#25433a]">Every little thing, with love.</p><p className="mt-3 text-sm leading-6 text-[#25433a]/65">A new home for easier, more confident choices.</p></div></div></div><div className="absolute -bottom-5 -left-4 rounded-2xl bg-white px-4 py-3 shadow-lg sm:-left-10"><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-[#d9776a]">Made for you</p><p className="mt-1 text-sm font-extrabold text-[#25433a]">Simple, useful, kind.</p></div></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-18 sm:px-8 md:py-24"><div className="max-w-xl"><p className="text-sm font-extrabold uppercase tracking-[0.14em] text-[#d9776a]">The MishBaby way</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-[-0.045em] text-[#25433a]">Less searching. More feeling ready.</h2></div><div className="mt-11 grid gap-5 md:grid-cols-3">{values.map(([icon, title, body]) => <article key={title} className="rounded-3xl border border-[#25433a]/8 bg-white p-7 shadow-[0_12px_30px_-24px_rgba(37,67,58,.45)]"><span className="grid size-11 place-items-center rounded-2xl bg-[#fff0eb] text-xl text-[#d9776a]">{icon}</span><h3 className="mt-6 text-lg font-extrabold text-[#25433a]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#25433a]/65">{body}</p></article>)}</div></section>
    <section className="mx-auto max-w-6xl px-5 pb-18 sm:px-8 md:pb-24"><div className="rounded-[2rem] bg-[#25433a] px-7 py-12 text-center text-white sm:px-12"><p className="text-sm font-extrabold uppercase tracking-[0.14em] text-[#f6c9c0]">Coming together</p><h2 className="mx-auto mt-3 max-w-xl font-display text-4xl font-semibold leading-tight tracking-[-0.045em]">A more helpful way to find what your family needs.</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-white/70">We’re just getting started. Soon, you’ll find trusted recommendations, useful collections, and easier ways to compare offers.</p></div></section>
  </main><Footer /></div>;
}
